// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: stt.proto

package sttpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Audio format hint ──────────────────────────────────────────────────────
type AudioFormat int32

const (
	AudioFormat_ENCODED       AudioFormat = 0 // WebM / OGG / MP3 — decode with ffmpeg (file streaming)
	AudioFormat_RAW_PCM_S16LE AudioFormat = 1 // Raw 16-kHz mono int16 — direct VAD (real-time mic)
)

// Enum value maps for AudioFormat.
var (
	AudioFormat_name = map[int32]string{
		0: "ENCODED",
		1: "RAW_PCM_S16LE",
	}
	AudioFormat_value = map[string]int32{
		"ENCODED":       0,
		"RAW_PCM_S16LE": 1,
	}
)

func (x AudioFormat) Enum() *AudioFormat {
	p := new(AudioFormat)
	*p = x
	return p
}

func (x AudioFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_stt_proto_enumTypes[0].Descriptor()
}

func (AudioFormat) Type() protoreflect.EnumType {
	return &file_stt_proto_enumTypes[0]
}

func (x AudioFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat.Descriptor instead.
func (AudioFormat) EnumDescriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

// ─── Messages ───────────────────────────────────────────────────────────────
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                // Audio payload
	SampleRate    uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // Hz; ignored for ENCODED format
	Format        AudioFormat            `protobuf:"varint,3,opt,name=format,proto3,enum=stt.AudioFormat" json:"format,omitempty"`
	EndOfStream   bool                   `protobuf:"varint,4,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"` // Signal: no more data, flush VAD buffer
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                             // ISO-639-1 or "" for auto-detect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetFormat() AudioFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_ENCODED
}

func (x *AudioChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *AudioChunk) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type TranscriptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                       // Transcribed text
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // true = VAD end-of-speech detected, Whisper ran
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`               // Detected language code
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`         // Average log-prob proxy
	Segments      []*Segment             `protobuf:"bytes,5,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptResult) Reset() {
	*x = TranscriptResult{}
	mi := &file_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptResult) ProtoMessage() {}

func (x *TranscriptResult) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptResult.ProtoReflect.Descriptor instead.
func (*TranscriptResult) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptResult) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscriptResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscriptResult) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         float32                `protobuf:"fixed32,1,opt,name=start,proto3" json:"start,omitempty"`
	End           float32                `protobuf:"fixed32,2,opt,name=end,proto3" json:"end,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Segment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ModelSize     string                 `protobuf:"bytes,2,opt,name=model_size,json=modelSize,proto3" json:"model_size,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	ComputeType   string                 `protobuf:"bytes,4,opt,name=compute_type,json=computeType,proto3" json:"compute_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_stt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetModelSize() string {
	if x != nil {
		return x.ModelSize
	}
	return ""
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthResponse) GetComputeType() string {
	if x != nil {
		return x.ComputeType
	}
	return ""
}

var File_stt_proto protoreflect.FileDescriptor

const file_stt_proto_rawDesc = "" +
	"\n" +
	"\tstt.proto\x12\x03stt\"\xab\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12(\n" +
	"\x06format\x18\x03 \x01(\x0e2\x10.stt.AudioFormatR\x06format\x12\"\n" +
	"\rend_of_stream\x18\x04 \x01(\bR\vendOfStream\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\xa7\x01\n" +
	"\x10TranscriptResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12(\n" +
	"\bsegments\x18\x05 \x03(\v2\f.stt.SegmentR\bsegments\"E\n" +
	"\aSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x02R\x03end\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x0f\n" +
	"\rHealthRequest\"\x82\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"model_size\x18\x02 \x01(\tR\tmodelSize\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12!\n" +
	"\fcompute_type\x18\x04 \x01(\tR\vcomputeType*-\n" +
	"\vAudioFormat\x12\v\n" +
	"\aENCODED\x10\x00\x12\x11\n" +
	"\rRAW_PCM_S16LE\x10\x012\x7f\n" +
	"\n" +
	"STTService\x12>\n" +
	"\x10TranscribeStream\x12\x0f.stt.AudioChunk\x1a\x15.stt.TranscriptResult(\x010\x01\x121\n" +
	"\x06Health\x12\x12.stt.HealthRequest\x1a\x13.stt.HealthResponseB=Z;github.com/QosmuratSamat0/Noona-AI/backend/pkg/pb/stt;sttpbb\x06proto3"

var (
	file_stt_proto_rawDescOnce sync.Once
	file_stt_proto_rawDescData []byte
)

func file_stt_proto_rawDescGZIP() []byte {
	file_stt_proto_rawDescOnce.Do(func() {
		file_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)))
	})
	return file_stt_proto_rawDescData
}

var file_stt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stt_proto_goTypes = []any{
	(AudioFormat)(0),         // 0: stt.AudioFormat
	(*AudioChunk)(nil),       // 1: stt.AudioChunk
	(*TranscriptResult)(nil), // 2: stt.TranscriptResult
	(*Segment)(nil),          // 3: stt.Segment
	(*HealthRequest)(nil),    // 4: stt.HealthRequest
	(*HealthResponse)(nil),   // 5: stt.HealthResponse
}
var file_stt_proto_depIdxs = []int32{
	0, // 0: stt.AudioChunk.format:type_name -> stt.AudioFormat
	3, // 1: stt.TranscriptResult.segments:type_name -> stt.Segment
	1, // 2: stt.STTService.TranscribeStream:input_type -> stt.AudioChunk
	4, // 3: stt.STTService.Health:input_type -> stt.HealthRequest
	2, // 4: stt.STTService.TranscribeStream:output_type -> stt.TranscriptResult
	5, // 5: stt.STTService.Health:output_type -> stt.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stt_proto_init() }
func file_stt_proto_init() {
	if File_stt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stt_proto_goTypes,
		DependencyIndexes: file_stt_proto_depIdxs,
		EnumInfos:         file_stt_proto_enumTypes,
		MessageInfos:      file_stt_proto_msgTypes,
	}.Build()
	File_stt_proto = out.File
	file_stt_proto_goTypes = nil
	file_stt_proto_depIdxs = nil
}
