// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: stt.proto

package sttpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	STTService_TranscribeStream_FullMethodName = "/stt.STTService/TranscribeStream"
	STTService_Health_FullMethodName           = "/stt.STTService/Health"
)

// STTServiceClient is the client API for STTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─── Service ─────────────────────────────────────────────────────────────────
type STTServiceClient interface {
	// Bidirectional stream: client sends AudioChunk, server responds with TranscriptResult.
	// Multiple TranscriptResult messages may be emitted per stream (one per speech segment).
	TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptResult], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type sTTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSTTServiceClient(cc grpc.ClientConnInterface) STTServiceClient {
	return &sTTServiceClient{cc}
}

func (c *sTTServiceClient) TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &STTService_ServiceDesc.Streams[0], STTService_TranscribeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, TranscriptResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STTService_TranscribeStreamClient = grpc.BidiStreamingClient[AudioChunk, TranscriptResult]

func (c *sTTServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, STTService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// STTServiceServer is the server API for STTService service.
// All implementations must embed UnimplementedSTTServiceServer
// for forward compatibility.
//
// ─── Service ─────────────────────────────────────────────────────────────────
type STTServiceServer interface {
	// Bidirectional stream: client sends AudioChunk, server responds with TranscriptResult.
	// Multiple TranscriptResult messages may be emitted per stream (one per speech segment).
	TranscribeStream(grpc.BidiStreamingServer[AudioChunk, TranscriptResult]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSTTServiceServer()
}

// UnimplementedSTTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSTTServiceServer struct{}

func (UnimplementedSTTServiceServer) TranscribeStream(grpc.BidiStreamingServer[AudioChunk, TranscriptResult]) error {
	return status.Error(codes.Unimplemented, "method TranscribeStream not implemented")
}
func (UnimplementedSTTServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSTTServiceServer) mustEmbedUnimplementedSTTServiceServer() {}
func (UnimplementedSTTServiceServer) testEmbeddedByValue()                    {}

// UnsafeSTTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to STTServiceServer will
// result in compilation errors.
type UnsafeSTTServiceServer interface {
	mustEmbedUnimplementedSTTServiceServer()
}

func RegisterSTTServiceServer(s grpc.ServiceRegistrar, srv STTServiceServer) {
	// If the following call panics, it indicates UnimplementedSTTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&STTService_ServiceDesc, srv)
}

func _STTService_TranscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(STTServiceServer).TranscribeStream(&grpc.GenericServerStream[AudioChunk, TranscriptResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STTService_TranscribeStreamServer = grpc.BidiStreamingServer[AudioChunk, TranscriptResult]

func _STTService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STTServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: STTService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STTServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// STTService_ServiceDesc is the grpc.ServiceDesc for STTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var STTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stt.STTService",
	HandlerType: (*STTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _STTService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranscribeStream",
			Handler:       _STTService_TranscribeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stt.proto",
}
