# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"z\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12 \n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x10.stt.AudioFormat\x12\x15\n\rend_of_stream\x18\x04 \x01(\x08\x12\x10\n\x08language\x18\x05 \x01(\t\"x\n\x10TranscriptResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x1e\n\x08segments\x18\x05 \x03(\x0b\x32\x0c.stt.Segment\"3\n\x07Segment\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"Z\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmodel_size\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompute_type\x18\x04 \x01(\t*-\n\x0b\x41udioFormat\x12\x0b\n\x07\x45NCODED\x10\x00\x12\x11\n\rRAW_PCM_S16LE\x10\x01\x32\x7f\n\nSTTService\x12>\n\x10TranscribeStream\x12\x0f.stt.AudioChunk\x1a\x15.stt.TranscriptResult(\x01\x30\x01\x12\x31\n\x06Health\x12\x12.stt.HealthRequest\x1a\x13.stt.HealthResponseB=Z;github.com/QosmuratSamat0/Noona-AI/backend/pkg/pb/stt;sttpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/QosmuratSamat0/Noona-AI/backend/pkg/pb/stt;sttpb'
  _globals['_AUDIOFORMAT']._serialized_start=426
  _globals['_AUDIOFORMAT']._serialized_end=471
  _globals['_AUDIOCHUNK']._serialized_start=18
  _globals['_AUDIOCHUNK']._serialized_end=140
  _globals['_TRANSCRIPTRESULT']._serialized_start=142
  _globals['_TRANSCRIPTRESULT']._serialized_end=262
  _globals['_SEGMENT']._serialized_start=264
  _globals['_SEGMENT']._serialized_end=315
  _globals['_HEALTHREQUEST']._serialized_start=317
  _globals['_HEALTHREQUEST']._serialized_end=332
  _globals['_HEALTHRESPONSE']._serialized_start=334
  _globals['_HEALTHRESPONSE']._serialized_end=424
  _globals['_STTSERVICE']._serialized_start=473
  _globals['_STTSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
