# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import stt_pb2 as stt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTServiceStub(object):
    """─── Service ─────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeStream = channel.stream_stream(
                '/stt.STTService/TranscribeStream',
                request_serializer=stt__pb2.AudioChunk.SerializeToString,
                response_deserializer=stt__pb2.TranscriptResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/stt.STTService/Health',
                request_serializer=stt__pb2.HealthRequest.SerializeToString,
                response_deserializer=stt__pb2.HealthResponse.FromString,
                _registered_method=True)


class STTServiceServicer(object):
    """─── Service ─────────────────────────────────────────────────────────────────
    """

    def TranscribeStream(self, request_iterator, context):
        """Bidirectional stream: client sends AudioChunk, server responds with TranscriptResult.
        Multiple TranscriptResult messages may be emitted per stream (one per speech segment).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=stt__pb2.AudioChunk.FromString,
                    response_serializer=stt__pb2.TranscriptResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=stt__pb2.HealthRequest.FromString,
                    response_serializer=stt__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stt.STTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stt.STTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTService(object):
    """─── Service ─────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stt.STTService/TranscribeStream',
            stt__pb2.AudioChunk.SerializeToString,
            stt__pb2.TranscriptResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stt.STTService/Health',
            stt__pb2.HealthRequest.SerializeToString,
            stt__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
