import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  shell: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  flex: { flex: 1 },
  loginWrap: { flex: 1, padding: 20, justifyContent: 'center' },
  loginCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    paddingHorizontal: 24,
    paddingVertical: 34,
    borderWidth: 1,
    borderColor: colors.border,
  },
  brandBlock: { alignItems: 'center', marginBottom: 30 },
  brandTitle: { color: colors.text, fontSize: 28, fontWeight: '800' },
  brandSubtitle: { color: colors.muted, fontSize: 15, fontWeight: '600', marginTop: 8 },
  field: { marginBottom: 20 },
  fieldLabel: { color: colors.text, fontSize: 14, fontWeight: '700', marginBottom: 8 },
  input: {
    height: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
    paddingHorizontal: 16,
  },
  forgotBtn: { alignSelf: 'flex-end', marginBottom: 24 },
  greenText: { color: colors.green, fontWeight: '700' },
  outlineButton: {
    minHeight: 54,
    borderRadius: 12,
    backgroundColor: colors.green,
    borderWidth: 1,
    borderColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineButtonText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  disabled: { opacity: 0.65 },
  orRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginVertical: 28 },
  line: { flex: 1, height: 1, backgroundColor: colors.border },
  muted: { color: colors.muted, fontSize: 16, fontWeight: '600' },
  googleButton: {
    minHeight: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 24,
  },
  googleLetter: { color: '#4285f4', fontSize: 18, fontWeight: '900' },
  googleText: { color: colors.text, fontSize: 15, fontWeight: '800', textAlign: 'center' },
  createText: { color: colors.muted, textAlign: 'center', marginTop: 22, fontSize: 16, fontWeight: '700' },
  screen: { flex: 1, backgroundColor: colors.bg, paddingBottom: 94 },
  header: {
    minHeight: 76,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingHorizontal: 28,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerTitle: { color: colors.text, fontSize: 21, fontWeight: '900' },
  pill: { backgroundColor: colors.greenSoft, borderRadius: 22, paddingHorizontal: 16, paddingVertical: 8 },
  pillText: { color: '#1d4ed8', fontSize: 14, fontWeight: '800' },
  content: { padding: 20, gap: 16 },
  hello: { color: colors.text, fontSize: 24, fontWeight: '900' },
  subText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  metric: {
    width: '48%',
    minHeight: 116,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    justifyContent: 'center',
  },
  metricValueRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  metricValue: { color: colors.text, fontSize: 30, fontWeight: '900' },
  metricLabel: { color: colors.muted, fontSize: 14, fontWeight: '700', marginTop: 4 },
  panel: { backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 18 },
  panelTitle: { color: colors.text, fontSize: 18, fontWeight: '900', marginBottom: 14 },
  heatRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 8 },
  heatLabel: { color: colors.text, width: 120, fontSize: 14, fontWeight: '700' },
  heatTrack: { flex: 1, height: 10, borderRadius: 6, backgroundColor: colors.border, overflow: 'hidden' },
  heatFill: { height: '100%', borderRadius: 6 },
  heatValue: { color: colors.muted, width: 44, textAlign: 'right', fontSize: 14, fontWeight: '800' },
  primaryButton: {
    minHeight: 54,
    borderRadius: 12,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '900' },
  chatHeader: {
    minHeight: 96,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingHorizontal: 22,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#1d4ed8', fontSize: 20, fontWeight: '900' },
  online: { color: colors.success, fontSize: 14, fontWeight: '800' },
  chatContent: { padding: 20, gap: 14 },
  messageBlock: { gap: 8 },
  bubble: { maxWidth: '86%', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12, borderWidth: 1 },
  coachBubble: { alignSelf: 'flex-start', backgroundColor: colors.surface, borderColor: colors.border },
  userBubble: { alignSelf: 'flex-end', backgroundColor: colors.green, borderColor: colors.green },
  bubbleText: { color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 22 },
  userBubbleText: { color: colors.white },
  playRow: {
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 8,
  },
  playText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  correctionCard: {
    alignSelf: 'flex-start',
    maxWidth: '82%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
  },
  correctionTitle: { color: colors.muted, fontSize: 15, fontWeight: '900', marginBottom: 8 },
  correctionLine: { fontSize: 17, fontWeight: '800' },
  correctionNote: { color: colors.text, marginTop: 6, fontSize: 15, fontWeight: '700' },
  strike: { color: colors.red, textDecorationLine: 'line-through', fontWeight: '800' },
  processingRow: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 10 },
  speakerBar: {
    minHeight: 122,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  micButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingButton: { backgroundColor: colors.red },
  speakerTitle: { color: colors.white, fontSize: 21, fontWeight: '900' },
  speakerTitleDark: { color: colors.text, fontSize: 16, fontWeight: '900' },
  speakerSub: { color: colors.muted, fontSize: 13, fontWeight: '700', marginTop: 2 },
  composerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  composerInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    color: colors.text,
    backgroundColor: colors.white,
    fontSize: 15,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabs: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 94,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
  },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 6 },
  tabLabel: { color: colors.muted, fontSize: 15, fontWeight: '800' },
  tabLabelActive: { color: colors.green },
  statRow: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 12 },
  statText: { color: colors.text, fontSize: 15, marginTop: 4 },
  profileAvatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: colors.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  profileAvatarText: { color: '#0d4f3e', fontSize: 34, fontWeight: '900' },
  profileName: { color: colors.text, fontSize: 24, fontWeight: '900', marginBottom: 6 },
});
